# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8154518c08a148f60f4daebc0422618fe945cf374cbd45bf344db76c4f990e90b4bc89f00992fa3aa370c46af1f7835ed9417713daf76ee769f052e83c10f546

test:
  secret_key_base: 92dd3f69eec55af252fdfd5cb6811efb20e50707059bb8d80a29efa0fd515b8ce537cde638a1a00669ba0978efb820af23cd36afd1aac988fba51e4e9aa8883b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
